### ISSUE TITLE
Missing countries

### ISSUE THREAD

**Issue by hersche** [porimol/countryinfo#13]
Hey,

thanks for your work. I found that serbia is not existing in your project yet and therefore not found. Would be nice if this is included.

https://en.wikipedia.org/wiki/Serbia

If you would prefer a PR with a such json, let me know and i will take the time.

**Comment by porimol** [comment]
Hey @hersche ,

Please make a PR.

**Comment by tommycarstensen** [comment]
Great stuff guys. The following countries (or synonyms) seem to be missing:
Andorra
Bahamas
Brunei Darussalam
Congo
Cote dIvoire
Eswatini
Holy See
Kosovo
Myanmar
North Macedonia
Palestine
Serbia
United Republic of Tanzania
United States of America

**Comment by porimol** [comment]
Hey @tommycarstensen ,

Thanks for your interest!

Would you please make PR!

**Comment by misteliy** [comment]
United States of America => 'United States'

**Comment by hersche** [comment]
I will change the title then to "Countries missing".

@porimol did you saw my PR? Hope it's fine as it is.

**Comment by porimol** [comment]
Hey @hersche ,

Sorry, I was a little bit busy. ASAP, I'll review and merge.

**Comment by drblahdblah** [comment]
> Hey @hersche ,
> 
> Sorry, I was a little bit busy. ASAP, I'll review and merge.

Is there any news on this PR? I love this library but adding these countries would be great!

**Comment by porimol** [comment]
Hi @hersche,

Merged your PR.


Thanks :)
