### ISSUE TITLE
Add capital coordinates?

### ISSUE THREAD

**Issue by DavidBreuer** [porimol/countryinfo#17]
Hi, thanks for the nice package! Would you be interested in an "enhancement" PR which adds the capital's coordinates (lat/lng), e.g. via a method `.capital_latlng()` or whatever you suggest as a suitable name? If you think this is helpful, I'm happy to create a PR.

**Comment by N1x0** [comment]
@DavidBreuer if you don't have all of those coords let me know I'd be happy to help eith some of the manual collection

**Comment by porimol** [comment]
Hey @DavidBreuer ,
Sure, please make a PR and the method name `.capital_latlng()` sound good to me.

**Comment by porimol** [comment]
Merged
