### ISSUE TITLE
Encoding problem 

### ISSUE THREAD

**Issue by hamza-hadda** [porimol/countryinfo#20]
'm trying to use **countryinfo** with django 2.2 to get the countries informations :
when I tried to get this :
```
country = 'Morocco' 
information = CountryInfo(country)
```
I get this error: 
`'charmap' codec can't decode byte 0x81 in position 49: character maps to <undefined>
`

**Comment by porimol** [comment]
@hamza-hadda How did you installed using PyPi or source code?

**Comment by hamza-hadda** [comment]
Pypi
What is the difference?

**Comment by porimol** [comment]
@hamza-hadda would you please update the version of `countryinfo` package?

I believe after version update it'll be resolve.


Thanks

**Comment by hamza-hadda** [comment]
I use the last version in PyPi 0.1.0

**Comment by porimol** [comment]
@hamza-hadda the latest version is 0.1.2
