### ISSUE TITLE
Documentation enhancement

### ISSUE THREAD

**Issue by konstantinstadler** [porimol/countryinfo#4]
Hi,
Great package!
Good you mention which data sources you are using in the readme?
Also, perhaps for which year the data is valid (e.g. important for population, but also for changing borders, ...).
Thanks for the package!
Best
kst

**Comment by porimol** [comment]
Hi @konstantinstadler ,

Thanks for your nice complement.
Yes, I have mentioned the source of data. You may find [here in the readme](https://github.com/porimol/countryinfo#special-thanks)
Though I have collected data from third-party source, even then I will try to check the cross validation.

Thanks
