### ISSUE TITLE
Wales and Scotland json are not complet

### ISSUE THREAD

**Issue by JonathanRamier** [porimol/countryinfo#5]
Great Job for this library, It 's a country library complete, I use it with Django Rest Framework. 

__Two Element I modify to on library comportement.__
* The first is ordering the country by name because the first was monaco.
* the second is Wales and scotland json file are not filled like others

but it a good lib. I hope you will have more stars

**Comment by porimol** [comment]
Hey @JonathanRamier, Have a look.
Still if you see anything is missing please feel free to send PR!

`from countryinfo import CountryInfo

country = CountryInfo('Scotland')
country.info()
{'name': 'Scotland', 'flag': '', 'geoJSON': {}, 'ISO': {'alpha2': '', 'alpha3': ''}, 'provinces': ['Aberdeen City', 'Aberdeenshire', 'Angus', 'Argyll and Bute', 'City of Edinburgh', 'Clackmannanshire', 'Dumfries and Galloway', 'Dundee City', 'East Ayrshire', 'East Dunbartonshire', 'East Lothian', 'East Renfrewshire', 'Eilean Siar (Western Isles)', 'Falkirk', 'Fife', 'Glasgow City', 'Highland', 'Inverclyde', 'Midlothian', 'Moray', 'North Ayrshire', 'North Lanarkshire', 'Orkney Islands', 'Perth and Kinross', 'Renfrewshire', 'Shetland Islands', 'South Ayrshire', 'South Lanarkshire', 'Stirling', 'The Scottish Borders', 'West Dunbartonshire', 'West Lothian'], 'tld': [], 'wiki': 'http://en.wikipedia.org/wiki/scotland'}`
