### ISSUE TITLE
is this library still maintained ?

### ISSUE THREAD

**Issue by MehdiDRISSIB** [porimol/countryinfo#71]

**Comment by porimol** [comment]
Hi @MehdiDRISSIB, 

Yes it is! Recently I started revamp the package but I can't promise when it will finish as I used to develop this package whenever I have free times.

You can look into [this branch](https://github.com/porimol/countryinfo/tree/revamp).

**Comment by MehdiDRISSIB** [comment]
many thanks for your answer. we are waiting for the new version

**Comment by MehdiDRISSIB** [comment]
Hello is it possible to release a new version of this package with latest updates please ? 
`CountryInfo('AD').region()`
throws an error 
`*** KeyError: 'ad'`

**Comment by MehdiDRISSIB** [comment]
Many thanks @porimol for this good news ! We are happy for this new release but when I

`pip install countryinfo`
or
`pip install countryinfo==1.0.0`

I get

`ERROR: Could not find a version that satisfies the requirement countryinfo==1.0.0 (from versions: 0.1.0, 0.1.2)`
